name: WhosOnline
main: net.infinitecoder.whosonline.WhosOnline
version: 1.0
description: 'Who is on servers'
author: InfiniteCoder
commands:
  setdata:
    usage: |
       /setdata <server name> <server address>
       Example: /setdata Hypixel mc.hypixel.net
    description: Set's server data
    permission: whosonline.setdata